version: '3.5'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-1
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    env_file:
      - env/zookeeper.env
    healthcheck:
      test: /bin/sh -c '[ \"imok\" = \"$$(echo ruok | nc -w 1 127.0.0.1 2181)\" ]' || exit 1
      interval: 1m
    volumes:
      - zookeeper-1-data:/var/lib/zookeeper/data/
      - zookeeper-1-log:/var/lib/zookeeper/log/

  kafka-1:
    image: confluentinc/cp-kafka
    hostname: kafka-1
    container_name: kafka-1
    stop_grace_period: 5m
    depends_on:
      - zookeeper-1
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - env/kafka.env
    volumes:
      - kafka-1-data:/var/lib/kafka/data/

  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper-1
      - kafka-1
    ports:
      - "8081:8081"
    env_file:
      - env/schema-registry.env

  simple:
    hostname: simple
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - "8040:8080"
    entrypoint:
      - "java"
      - "-jar"
      - "target/kafka-salsa.jar"
      - "simple"
      - "--application-id=simple"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--brokers=kafka-1:9092"
      - "--schema-registry-url=http://schema-registry:8081"

  sampling:
    hostname: sampling
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - "8050:8080"
    entrypoint:
      - "java"
      - "-jar"
      - "target/kafka-salsa.jar"
      - "sampling"
      - "--application-id=sampling"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--brokers=kafka-1:9092"
      - "--schema-registry-url=http://schema-registry:8081"
      - "--buffer=100"

  range-key:
    hostname: range-key
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - "8060:8080"
    entrypoint:
      - "java"
      - "-jar"
      - "target/kafka-salsa.jar"
      - "range-key"
      - "--application-id=range-key"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--brokers=kafka-1:9092"
      - "--schema-registry-url=http://schema-registry:8081"

  segmented:
    hostname: segmented
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - "8070:8080"
    entrypoint:
      - "java"
      - "-jar"
      - "target/kafka-salsa.jar"
      - "segmented"
      - "--application-id=segmented"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--brokers=kafka-1:9092"
      - "--schema-registry-url=http://schema-registry:8081"
      - "--segments=100"
      - "--pools=16"
      - "--nodesPerPool=131072"

volumes:
  zookeeper-1-data:
  zookeeper-1-log:
  kafka-1-data:
