/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.hpi.msd.salsa.serde.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RangeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5170709342480096099L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RangeKey\",\"namespace\":\"de.hpi.msd.salsa.serde.avro\",\"fields\":[{\"name\":\"nodeId\",\"type\":\"long\"},{\"name\":\"position\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RangeKey> ENCODER =
      new BinaryMessageEncoder<RangeKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RangeKey> DECODER =
      new BinaryMessageDecoder<RangeKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RangeKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RangeKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RangeKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RangeKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RangeKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RangeKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RangeKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RangeKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long nodeId;
  @Deprecated public long position;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RangeKey() {}

  /**
   * All-args constructor.
   * @param nodeId The new value for nodeId
   * @param position The new value for position
   */
  public RangeKey(java.lang.Long nodeId, java.lang.Long position) {
    this.nodeId = nodeId;
    this.position = position;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nodeId;
    case 1: return position;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nodeId = (java.lang.Long)value$; break;
    case 1: position = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'nodeId' field.
   * @return The value of the 'nodeId' field.
   */
  public long getNodeId() {
    return nodeId;
  }


  /**
   * Sets the value of the 'nodeId' field.
   * @param value the value to set.
   */
  public void setNodeId(long value) {
    this.nodeId = value;
  }

  /**
   * Gets the value of the 'position' field.
   * @return The value of the 'position' field.
   */
  public long getPosition() {
    return position;
  }


  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(long value) {
    this.position = value;
  }

  /**
   * Creates a new RangeKey RecordBuilder.
   * @return A new RangeKey RecordBuilder
   */
  public static de.hpi.msd.salsa.serde.avro.RangeKey.Builder newBuilder() {
    return new de.hpi.msd.salsa.serde.avro.RangeKey.Builder();
  }

  /**
   * Creates a new RangeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RangeKey RecordBuilder
   */
  public static de.hpi.msd.salsa.serde.avro.RangeKey.Builder newBuilder(de.hpi.msd.salsa.serde.avro.RangeKey.Builder other) {
    if (other == null) {
      return new de.hpi.msd.salsa.serde.avro.RangeKey.Builder();
    } else {
      return new de.hpi.msd.salsa.serde.avro.RangeKey.Builder(other);
    }
  }

  /**
   * Creates a new RangeKey RecordBuilder by copying an existing RangeKey instance.
   * @param other The existing instance to copy.
   * @return A new RangeKey RecordBuilder
   */
  public static de.hpi.msd.salsa.serde.avro.RangeKey.Builder newBuilder(de.hpi.msd.salsa.serde.avro.RangeKey other) {
    if (other == null) {
      return new de.hpi.msd.salsa.serde.avro.RangeKey.Builder();
    } else {
      return new de.hpi.msd.salsa.serde.avro.RangeKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for RangeKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RangeKey>
    implements org.apache.avro.data.RecordBuilder<RangeKey> {

    private long nodeId;
    private long position;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.hpi.msd.salsa.serde.avro.RangeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nodeId)) {
        this.nodeId = data().deepCopy(fields()[0].schema(), other.nodeId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.position)) {
        this.position = data().deepCopy(fields()[1].schema(), other.position);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RangeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(de.hpi.msd.salsa.serde.avro.RangeKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.nodeId)) {
        this.nodeId = data().deepCopy(fields()[0].schema(), other.nodeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.position)) {
        this.position = data().deepCopy(fields()[1].schema(), other.position);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'nodeId' field.
      * @return The value.
      */
    public long getNodeId() {
      return nodeId;
    }


    /**
      * Sets the value of the 'nodeId' field.
      * @param value The value of 'nodeId'.
      * @return This builder.
      */
    public de.hpi.msd.salsa.serde.avro.RangeKey.Builder setNodeId(long value) {
      validate(fields()[0], value);
      this.nodeId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nodeId' field has been set.
      * @return True if the 'nodeId' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nodeId' field.
      * @return This builder.
      */
    public de.hpi.msd.salsa.serde.avro.RangeKey.Builder clearNodeId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'position' field.
      * @return The value.
      */
    public long getPosition() {
      return position;
    }


    /**
      * Sets the value of the 'position' field.
      * @param value The value of 'position'.
      * @return This builder.
      */
    public de.hpi.msd.salsa.serde.avro.RangeKey.Builder setPosition(long value) {
      validate(fields()[1], value);
      this.position = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'position' field has been set.
      * @return True if the 'position' field has been set, false otherwise.
      */
    public boolean hasPosition() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'position' field.
      * @return This builder.
      */
    public de.hpi.msd.salsa.serde.avro.RangeKey.Builder clearPosition() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RangeKey build() {
      try {
        RangeKey record = new RangeKey();
        record.nodeId = fieldSetFlags()[0] ? this.nodeId : (java.lang.Long) defaultValue(fields()[0]);
        record.position = fieldSetFlags()[1] ? this.position : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RangeKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<RangeKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RangeKey>
    READER$ = (org.apache.avro.io.DatumReader<RangeKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.nodeId);

    out.writeLong(this.position);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.nodeId = in.readLong();

      this.position = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.nodeId = in.readLong();
          break;

        case 1:
          this.position = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










