apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-salsa
  labels:
    app: kafka-salsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-salsa
  template:
    metadata:
      labels:
        app: kafka-salsa
    spec:
      containers:
        - name: salsa-container
          image: torben96/kafka-salsa
          args:
            - --host
            - $(POD_IP)
            - --port
            - 8070
            - --brokers
            - $(KAFKA_HOSTS)
            - --schema-registry-url
            - $(SCHEMA_REGISTRY_URL)
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: kafka.hosts
                  name: kafka-salsa-configmap
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  key: schema.registry.url
                  name: kakfa-salsa-configmap
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
              name: rest-api
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-salsa
  labels:
    app: kafka-salsa
spec:
  type: LoadBalancer
  selector:
    app: kafka-salsa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
      name: rest-api